---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onepassword-token
  namespace: external-secrets-operator
spec:
  encryptedData:
    token: AgCooCxCouGQRwb+L3N1e+Mso/eJou7B6N6ZBeARmpz3fM/avPjQ6oOjCK9zfjc5jchGkS40y+Q8nreAYCOtU4IZiI+gK02wb/rdPSkMXR6Dupbp1w4p5yFw/9PcpBs+7aO1J3+fd+bmEdNQ4yUX7Lkr2AlKKhIdfBnX/x7R5T4IwdLoe/rgISyRQWAkddgRnCML5yV0Fc2YUUUsT9VzBQcb18eT6deN7pEXnVb1GBVHuC29sp+dxCXBuHUhPjuZo65XCEqjjOQCPQZhWTqSbuZpVW6H02TOgmgMg+1ZKKkFAkY+36uYUmq5rQTf4QkMLXRXz9eUEnLoc9ai0tzBuGz2g0V2ld/9B5FZ7dqTjNuhPTsEXDtG+qbzrB0+NrbqODnS4i9EB8o1PBP0hQeLiKrewzRadBbz+WYVxeuY2EKm38WCioxRIzwaRpqjn7gN8sbRzUWh+qkXc0r6j8BDoEeZ2Mm8vA53dCWNJj03RufSZviLVXvieJ/rvp16qKGJ8gyAnRLx3Uy0xwhSpkJ0N8gBxvywJ4rK3dQSP92Et4fmiax7kuJ6hbPc/hVtlb5Bqcj2dDgcLHhtTM3eDT9DTl9gATJmZMtMN8RivAI4AeN2tZXCZoNIPxkeoBUmdHx+wiC8rxkaofFAF2i5jLXbaiiFMxWrlT7oQiN7DN7MfTwbSie4LrdatYHt6MUEKtJDevs6i56C696dpgS9/Km9xnaeyW05QSIQ7ZAqVQIL/1SmOUEbMB2inNUsip1VYIRkJhnzCyPBTj9Ds7KJvq3eXYoGFd24bqZaHuJjBDhEmNnwwYkPhWnbl5htaQYsAoRc+sRnfUchbHC5iK6r52x4twrFgnsPCTchmQubsoasEZSaQVLkmiM3H8OHqWHgNSem8Im1FZdFsHxyHGML3swIei4qXHQzA8ccAmQ4yCevt3Q8T1f6baAUblS0lF+UJBC4K8QeTEAhRyWiZjlQcydWSXwunnm7C72pORRlLasWzpd+Kia2Q/o6iOa/ac3njJxqsRauekempeskTFcTrBWM4cJJ2o6J1xIDrbdMc61WzrevE3GFUggLqwh+rLsNqry3ThzacCMM0G7aA3szur38q+bmcdFlDocCCcCGXWuBTmMRcrLFoT//gBKCXDlPfTBmc/8sF7hu6gCzOaPT6uSFDwMlxFlD/SHwfAhyr5/0KDtf9UPjj1rPrnPdO6YB3Q9o/2AgmY6QnOAgkAa3uJHufANPnDj3d8nsdxzsdiXar9mzBjupPCTDsmZevdwUCeBkziZZVVgxwnxqdqawrNlVRbwtxnanChJa3Oavwzpc2h3Kn8yfIILJS0Ka9baGaBkBY0Tz58zf3Vjd5MlRdPM7+szkd68aOVKwxTKIkKMRQz+UwDw7jEPIJ1rwNbzg/xB7tzMjlyhcHs1BBkQTneUyDdXfnp/4OcNF2/aUYViaetvy2ZOMWrnMdHkWfgOwe6ggCgTW9rJaTLX9A+bYFlaPR5kJUKMwdXTza83bOY2ndrUmMSw01wEcDbQ4+cR59EADVxSOzOvjbToh28TAmAmyKGpBJVA=
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: external-secrets-operator
