{
 "title": "Minecraft Players",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server Name",
    "query": {
     "query": "label_values(mc_player_online, job)"
    }
   },
   {
    "name": "player",
    "label": "Player",
    "query": {
     "query": "label_values(mc_player_online, name)"
    }
   },
   {
    "name": "statistic",
    "label": "Statistic",
    "query": {
     "query": "label_values(mc_player_statistic,statistic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online players",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mc_player_online{name=~\"$player\", server_name=~\"$server_name\"}) without (uid)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "$statistic over time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"$statistic\", server_name=~\"$server_name\"}) without (player_uid)",
     "legendFormat": "{{player_name}}: {{statistic}}"
    }
   ]
  },
  {
   "title": "$statistic by player",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"$statistic\", server_name=~\"$server_name\"}) without (player_uid)",
     "legendFormat": "{{player_name}}: {{statistic}}"
    }
   ]
  }
 ]
}