{
 "title": "Minecraft",
 "tags": [ "minecraft" ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server Name",
    "query": {
     "query": "label_values(mc_players_total, server_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Players",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_players_total{server_name=~\"$server_name\"}",
     "legendFormat": "Unique"
    },
    {
     "expr": "sum(mc_players_online_total{server_name=~\"$server_name\"}) by (world)",
     "legendFormat": "Online ({{world}})"
    },
    {
     "expr": "mc_whitelisted_players{server_name=~\"$server_name\"}",
     "legendFormat": "Whitelisted"
    }
   ]
  },
  {
   "title": "Players Online",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mc_players_online_total{server_name=~\"$server_name\"})"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=~\"$server_name\"} - scalar(mc_jvm_memory{type='free', server_name=~\"$server_name\"})"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mc_tps{server_name=~\"$server_name\"}"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{server_name=~\"$server_name\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "mc_jvm_memory{type='max', server_name=~\"$server_name\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "mc_jvm_memory{type='allocated', server_name=~\"$server_name\"} - scalar(mc_jvm_memory{type='free', server_name=~\"$server_name\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (mc_entities_total{server_name=~\"$server_name\"}) by (world)",
     "legendFormat": "{{world}}_total"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mc_tps{server_name=~\"$server_name\"}",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(mc_jvm_threads_current{server_name=~\"$server_name\"})",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "sum by (state) (mc_jvm_threads_state{server_name=~\"$server_name\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Unique Players",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "mc_players_total{server_name=~\"$server_name\"}",
     "legendFormat": "unique players"
    }
   ]
  },
  {
   "title": "Villagers",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (mc_villagers_total{server_name=~\"$server_name\"}) by (world, level, profession)",
     "legendFormat": "{{world}}:  {{profession}}  (lv{{level}})"
    }
   ]
  },
  {
   "title": "Entity",
   "type": "stat",
   "gridPos": { "h": 27, "w": 24, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(sum (mc_entities_total{server_name=~\"$server_name\"}) by (type))",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}