apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry-operator-system

resources:
  - ../opentelemetry

patches:
  - target:
      group: opentelemetry.io
      kind: OpenTelemetryCollector
      name: otelcol-ds
    path: patches/metricstransform-rename.hostmetrics.cpu.yaml
  - target:
      group: opentelemetry.io
      kind: OpenTelemetryCollector
      name: otelcol-ds
    path: patches/resource.attributes.yaml
  - target:
      group: opentelemetry.io
      kind: OpenTelemetryCollector
      name: otelcol-ds
    path: patches/transform-metrics.label-rename.yaml
