{
 "title": "GatewayClasses",
 "tags": [
  "gateway-api",
  "gateway-api-state"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "gatewayclass",
    "label": "Gateway Class",
    "query": {
     "query": "label_values(gatewayapi_gatewayclass_info, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gatewayclass_info)"
    }
   ]
  },
  {
   "title": "Gateway Classes",
   "type": "table",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "expr": "gatewayapi_gatewayclass_created"
    },
    { "expr": "gatewayapi_gatewayclass_status" },
    { "expr": "gatewayapi_gatewayclass_info" }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_gatewayclass_status{type=\"Accepted\"} > 0)"
    }
   ]
  },
  {
   "title": "Gateways (by GatewayClass)",
   "type": "table",
   "gridPos": { "h": 6, "w": 22, "x": 2, "y": 6 },
   "targets": [
    { "expr": "gatewayapi_gateway_info" }
   ]
  }
 ]
}