{
 "title": "UDPRoutes",
 "description": "Visualisation of kubernetes Gateway API UDPRoute resources in your cluster.",
 "tags": [
  "gateway-api",
  "gateway-api-state"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "udproute",
    "label": "UDPRoute",
    "query": {
     "query": "label_values(gatewayapi_udproute_created, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "stat",
   "description": "Total number of UDPRoutes across all namespaces",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_udproute_created{name=~\"$udproute\"})"
    }
   ]
  },
  {
   "title": "Targeted Parents",
   "type": "stat",
   "description": "Total number of parents (e.g. Gateways) targeted by UDPRoutes",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_udproute_parent_info{name=~\"$udproute\"})"
    }
   ]
  },
  {
   "title": "Attached Parents",
   "type": "stat",
   "description": "Total number of parents (e.g. Gateways) attached to UDPRoutes",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gatewayapi_udproute_status_parent_info{name=~\"$udproute\"})"
    }
   ]
  },
  {
   "title": "UDPRoutes",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "gatewayapi_udproute_created{name=~\"$udproute\"}"
    },
    {
     "expr": "gatewayapi_udproute_parent_info{name=~\"$udproute\"}"
    },
    {
     "expr": "gatewayapi_udproute_status_parent_info{name=~\"$udproute\"}"
    }
   ]
  }
 ]
}