apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haproxy-controller

resources:
  - resources/namespace.yaml
  - resources/certificate.default.yaml
  - resources/gatewayclass.yaml
  # - resources/horizontal-pod-autoscaler.yaml

# patches:
#   - target:
#       group: apps
#       version: v1
#       kind: Deployment
#       name: haproxy-ingress
#       namespace: haproxy-ingress
#     path: patches/remove-deployment-replicas.yaml

helmCharts:
  - name: kubernetes-ingress
    namespace: haproxy-controller
    repo: https://haproxytech.github.io/helm-charts
    version: 1.45.1
    releaseName: haproxy-kubernetes-ingress
    includeCRDs: true
    valuesInline: {}
    valuesFile: values.yaml