apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    database: app
    host: postgres-rw.keycloak
    vendor: postgres
    usernameSecret:
      name: postgres-app
      key: username
    passwordSecret:
      name: postgres-app
      key: password
  http:
    httpEnabled: true
    tlsSecret: keycloak-tls
  hostname:
    hostname: keycloak.${K_INFRA_NAME}.${K_ZONE_NAME}
    admin: admin.keycloak.${K_INFRA_NAME}.${K_ZONE_NAME}
