apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  instances: 1
  db:
    database: app
    host: postgres-rw
    vendor: postgres
    usernameSecret:
      name: postgres-app
      key: username
    passwordSecret:
      name: postgres-app
      key: password
  http:
    httpEnabled: true
    tlsSecret: keycloak-tls
  ingress:
    className: haproxy
    annotations:
      haproxy-ingress.github.com/secure-backends: "true"
      # haproxy-ingress.github.io/ssl-passthrough: "true"
      # haproxy-ingress.github.io/ssl-redirect: "true"
  hostname:
    hostname: keycloak.${K_INFRA_NAME}.${K_ZONE_NAME}
  proxy:
    headers: xforwarded