apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: haproxy-ingress

resources:
  - resources/namespace.yaml
  - resources/certificate.default.yaml
  - resources/horizontal-pod-autoscaler.yaml
  - resources/gatewayclass.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: haproxy-ingress
      namespace: haproxy-ingress
    path: patches/remove-deployment-replicas.yaml

helmCharts:
  - name: haproxy-ingress
    namespace: haproxy-ingress
    repo: https://haproxy-ingress.github.io/charts
    version: 0.15.0
    releaseName: haproxy-ingress
    includeCRDs: true
    valuesInline: {}
    valuesFile: values.yaml