---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-ssh-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repo-creds
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: url
    remoteRef:
      key: ssh-credentials_argocd.rye.ninja
      property: url
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: type
    remoteRef:
      key: ssh-credentials_argocd.rye.ninja
      property: type
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
  - secretKey: sshPrivateKey
    remoteRef:
      key: ssh-credentials_argocd.rye.ninja
      property: sshPrivateKey
      conversionStrategy: Default	
      decodingStrategy: None
      metadataPolicy: None
