apiVersion: v1
kind: Secret
metadata:
  name: cluster-kubernetes.default.svc
  annotations:
    managed-by: argocd.argoproj.io
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: in-cluster
  server: https://kubernetes.default.svc
  config: |
    tlsClientConfig:
      insecure: true
