apiVersion: v1
kind: ConfigMap
metadata:
  name: kustomize-helm-envsubst-cm
  namespace: argocd
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomize-helm-envsubst
    spec: