apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../../applications/argocd

patches:
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: argocd-server-tls
    patch: |-
      - op: replace
        path: /spec/commonName
        value: argocd.rspot.rye.ninja
      - op: replace
        path: /spec/dnsNames/0
        value: argocd.rspot.rye.ninja
  - target:
      group: gateway.networking.k8s.io
      version: v1
      kind: Gateway
      name: eg-argocd
    patch: |-
      - op: replace
        path: /spec/listeners/0/hostname
        value: argocd.rspot.rye.ninja
  - target:
      group: ""
      version: v1
      kind: ConfigMap
      name: argocd-cm
    patch: |-
      - op: replace
        path: /data/url
        value: https://argocd.rspot.rye.ninja