apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opentelemetry-operator-system

resources:
  - ../../../applications/opentelemetry-groundcover

patches:
  - target:
      group: opentelemetry.io
      kind: OpenTelemetryCollector
      name: otelcol-ds
    path: groundcover-env.yaml