apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway-system

resources:
  - resources/namespace.yaml
  - resources/envoyproxy.yaml
  - resources/gatewayclass.yaml


helmCharts:
  - name: gateway-crds-helm
    namespace: envoy-gateway-system
    repo: oci://docker.io/envoyproxy
    version: 1.5.4
    releaseName: eg-crds
    includeCRDs: true
    valuesInline:
      crds:
        gatewayAPI:
          enabled: false
          channel: experimental
        envoyGateway:
          enabled: true
  - name: gateway-helm
    namespace: envoy-gateway-system
    repo: oci://docker.io/envoyproxy
    version: 1.5.4
    releaseName: eg
    includeCRDs: false
    valuesInline: {}
    valuesFile: values.yaml