apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: self-signed-ca
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        selector:
          matchLabels:
            rye.ninja/ldap-trust-enabled: "true"
        key: ca.crt
  target:
    configMap:
      key: root-certs.pem
    additionalFormats:
      jks:
        key: bundle.jks
        password: changeit
      pkcs12:
        key: bundle.p12
        password: ''
    namespaceSelector:
      matchLabels:
        rye.ninja/ldap-trust-enabled: "true"