apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openldap-tls
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  isCA: false
  subject:
    countries:
      - US
    provinces:
      - Minnesota
    localities:
      - Bloominton
    organizations:
      - Ryezone Labs
    organizationalUnits:
      - OpenLDAP
  commonName: ldap.${K_INFRA_NAME}.${K_ZONE_NAME}
  dnsNames:
    - ldap.${K_INFRA_NAME}.${K_ZONE_NAME}
    - ldap-readonly.${K_INFRA_NAME}.${K_ZONE_NAME}
  secretName: openldap-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: zerossl-production
    kind: ClusterIssuer
    group: cert-manager.io