apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "ldap-admin-password"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: "30m"
  target:
    name: ldap-admin-password
    template:
      engineVersion: v2
      data:
        LDAP_ADMIN_PASSWORD: "{{ .password }}"
        LDAP_CONFIG_ADMIN_PASSWORD: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: "password-generator"