apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: password-generator
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  length: 32
  digits: 5
  symbols: 5
  symbolCharacters: "-_$@"
  noUpper: false
  allowRepeat: true