apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
  - name: trust-manager
    namespace: cert-manager
    repo: https://charts.jetstack.io
    version: v0.16.0
    releaseName: trust-manager
    includeCRDs: true
    valuesInline: {}
    valuesFile: values.yaml