global:
  ldapDomain: "dc=rye,dc=ninja"

env:
 LDAP_SKIP_DEFAULT_TREE: "yes"
 LDAP_ALLOW_ANON_BINDING: 'no'

customLdifFiles:
  00-root.ldif: |-
    # Root creation
    dn: dc=rye,dc=ninja
    dc: rye.ninja
    objectClass: dcObject
  01-org.ldif: |-
    # Organization creation
    dn: o=rspot,dc=rye,dc=ninja
    objectClass: organization
    o: rspot
  02-ou-users.ldif: |-
    # Users OU
    dn: ou=users,o=rspot,dc=rye,dc=ninja
    objectClass: organizationalUnit
    ou: users
  02-ou-groups.ldif: |-
    # Groups OU
    dn: ou=groups,o=rspot,dc=rye,dc=ninja
    objectClass: organizationalUnit
    ou: groups
  03-ou-machines.ldif: |-
    # Machines OU
    dn: ou=machines,o=rspot,dc=rye,dc=ninja
    objectClass: organizationalUnit
    ou: machines
#   01-default-group.ldif: |-
#     dn: cn=myGroup,dc=example,dc=org
#     cn: myGroup
#     gidnumber: 500
#     objectclass: posixGroup
#     objectclass: top
#   02-default-user.ldif: |-
#     dn: cn=Jean Dupond,dc=example,dc=org
#     cn: Jean Dupond
#     gidnumber: 500
#     givenname: Jean
#     homedirectory: /home/users/jdupond
#     objectclass: inetOrgPerson
#     objectclass: posixAccount
#     objectclass: top
#     sn: Dupond
#     uid: jdupond
#     uidnumber: 1000
#     userpassword: {MD5}KOULhzfBhPTq9k7a9XfCGw==