global:
  ldapDomain: "dc=${K_ZONE_NAME}"

customLdifFiles:
  00-root.ldif: |-
    # Root creation
    dn: dc=${K_ZONE_NAME}
    objectClass: dcObject
  01-org.ldif: |-
    # Organization creation
    dn: o=${K_INFRA_NAME},dc=${K_ZONE_NAME}
    objectClass: organization
    o: Ryezone Labs (${K_INFRA_NAME}.${K_ZONE_NAME})
  02-ou-users.ldif: |-
    # Users OU
    dn: ou=users,o=${K_INFRA_NAME},dc=${K_ZONE_NAME}
    objectClass: organizationalUnit
    ou: users
  02-ou-groups.ldif: |-
    # Groups OU
    dn: ou=groups,dc=${K_INFRA_NAME},dc=${K_ZONE_NAME}
    objectClass: organizationalUnit
    ou: groups
  03-ou-machines.ldif: |-
    # Machines OU
    dn: ou=machines,dc=${K_INFRA_NAME},dc=${K_ZONE_NAME}
    objectClass: organizationalUnit
    ou: machines
#   01-default-group.ldif: |-
#     dn: cn=myGroup,dc=example,dc=org
#     cn: myGroup
#     gidnumber: 500
#     objectclass: posixGroup
#     objectclass: top
#   02-default-user.ldif: |-
#     dn: cn=Jean Dupond,dc=example,dc=org
#     cn: Jean Dupond
#     gidnumber: 500
#     givenname: Jean
#     homedirectory: /home/users/jdupond
#     objectclass: inetOrgPerson
#     objectclass: posixAccount
#     objectclass: top
#     sn: Dupond
#     uid: jdupond
#     uidnumber: 1000
#     userpassword: {MD5}KOULhzfBhPTq9k7a9XfCGw==