apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openldap

helmCharts:
  - name: openldap-stack-ha
    namespace: openldap
    repo: https://jp-gouin.github.io/helm-openldap/
    version: 4.3.3
    releaseName: openldap
    includeCRDs: true
    valuesInline: {}
    valuesFile: values.yaml
    additionalValuesFiles:
      - directory.values.yaml

configMapGenerator:
- name: rye-ninja-ldif
  files:
    - resources/ldif/00000-root.ldif
    - resources/ldif/00001-ou-infra.ldif
    - resources/ldif/00002-ou-users.ldif
    - resources/ldif/00003-ou-groups.ldif
    - resources/ldif/00004-ou-machines.ldif
    - resources/ldif/00100-ou-group-devops.ldif
    - resources/ldif/00101-ou-group-readonly.ldif
    - resources/ldif/01000-user-devops-admin.ldif
    - resources/ldif/01001-user-readonly.ldif

resources:
  - resources/namespace.yaml
  # - resources/certificate.openldap.yaml
  # - resources/certificate.self-signed-ca.yaml
  - resources/externalsecret.admin-password.yaml
  # - resources/issuer.self-signed-root-ca.yaml
  # - resources/issuer.ldap.yaml
  - resources/password.generator.yaml
  # - resources/bundle.self-signed-ca.yaml
  - resources/certificate.public.openldap.yaml

patches:
- patch: |
    - op: add
      path: /spec/volumeClaimTemplates/0/apiVersion
      value: v1
    - op: add
      path: /spec/volumeClaimTemplates/0/kind
      value: PersistentVolumeClaim
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: openldap
