apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openldap

helmCharts:
  - name: openldap-stack-ha
    namespace: openldap
    repo: https://jp-gouin.github.io/helm-openldap/
    version: 4.3.3
    releaseName: openldap
    includeCRDs: true
    valuesInline: {}
    valuesFile: values.yaml
    # additionalValuesFiles:
    #   - directory.values.yaml

resources:
  - resources/namespace.yaml
  # - resources/certificate.openldap.yaml
  # - resources/certificate.self-signed-ca.yaml
  - resources/externalsecret.admin-password.yaml
  # - resources/issuer.self-signed-root-ca.yaml
  # - resources/issuer.ldap.yaml
  - resources/password.generator.yaml
  # - resources/bundle.self-signed-ca.yaml
  - resources/certificate.public.openldap.yaml

patches:
- patch: |
    - op: add
      path: /spec/volumeClaimTemplates/0/apiVersion
      value: v1
    - op: add
      path: /spec/volumeClaimTemplates/0/kind
      value: PersistentVolumeClaim
  target:
    group: apps
    version: v1
    kind: StatefulSet
    name: openldap
