apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otelcol-ds
spec:
  mode: daemonset
  terminationGracePeriodSeconds: 600
  hostNetwork: true
  config:
    receivers:
      # Receive metrics from the Envoy Access Log Service
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/envoyalsreceiver
      # https://gateway.envoyproxy.io/v1.5/tasks/observability/proxy-accesslog/#ggrpc-access-log-serviceals-sink
      # Needs custom otelcollector image with the envoyalsreceiver included
      # https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder
      envoyals:
        endpoint: 0.0.0.0:4319
      hostmetrics:
        scrapers:
          # cpu:
          # disk:
          # filesystem:
          load:
          # memory:
          # network:
          # process:
          # processes:
          # paging:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15

    exporters:
      debug: {}

    service:
      pipelines:
        metrics:
          receivers: [otlp, hostmetrics]
          # receivers: [otlp, hostmetrics,  envoyals]
          processors: [memory_limiter]
          exporters: [debug]
        logs:
          receivers: [otlp]
          # receivers: [otlp, hostmetrics,  envoyals]
          processors: [memory_limiter]
          exporters: [debug]
        traces:
          receivers: [otlp]
          # receivers: [otlp, hostmetrics,  envoyals]
          processors: [memory_limiter]
          exporters: [debug]