---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.1password:8081
      vaults:
        Home_Lab: 1  # look in this vault first
#        shared: 2   # next look in here. error if not found
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-token
            namespace: external-secrets-operator
            key: token