apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 1password
resources:
  - resources/sealed-secrets-credentials.yaml
  - resources/sealed-secrets-token.yaml
  - ../../../applications/1password

patches:
- target:
    group: cert-manager.io
    version: v1
    kind: Certificate
    name: connect-api-tls
  patch: |-
    - op: replace
      path: /spec/commonName
      value: connect-api.rspot.rye.ninja
    - op: replace
      path: /spec/dnsNames/0
      value: connect-api.rspot.rye.ninja
- target:
    group: gateway.networking.k8s.io
    version: v1
    kind: Gateway
    name: eg-connect-api
  patch: |-
    - op: replace
      path: /spec/listeners/0/hostname
      value: connect-api.rspot.rye.ninja

- patch: |
    - op: replace
      path: /spec/rules/0/host
      value: connect.rspot.rye.ninja
    - op: replace
      path: /spec/tls/0/hosts/0
      value: connect.rspot.rye.ninja
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: connect
