---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: onepassword-token
  namespace: 1password
spec:
  encryptedData:
    token: AgA/TV9XAKIHlBcBjA42H2mqZavnmDwBG24BfyiUaO4mnYHVT7Xe/T3j/sYikphtYP6CmTy7naWRPtdS5GSpoIAQHfJwjzR93bSajg7C/VDIQNpZ5XNp0KpySTLq9EWy3Q78GOp03xc4IwyUj6UVtFokDuTFR5x4TQGuCTkhNmRdA/KZf/BmsAkFGUIksKJG018ytbpbaoONICpuaohmQeVOR/sSMUth2NFFKbwEHfGbFYuwIRIqRybuC42S7DmtjSu96fi+9epCluSgYHhe8us3jLMhGoaR7mGiVP4iZmphaE259tmLGBJf6XJsWnEeneqr2+tkkj2a/cl09MgfRK6RjnnwkAaRTwS399WBMdezPIakzeFaZzyS3W9lqJYHwem050bgcIX/bAaJdI6wsJMLeCs7BnOBBSRCrVTRmnkmYm9Z01OvSFZELkRtcfDU+kzz0GOoXlKHsbMn93VbTsC/hziMd74Iaug8XAOqn6Zcej008RewF8f9z7vAEuwaLIRdsyrkiFfReG28+4mFAVFhsWXXmipaGQMBQ4tqEipiOTNZnwHdld4Cz1aM24BC1zNSzR1ffl1FZzporUXihiuXyUxrAeH3LKLRgLrfoNJjNWhsGVW2pGriATKHP8wjfwnk7AgRBHmbaS3qTrFYouoC0yRLstAs5AYYICF7OuvW+GciOpzHKuL1dcLfaowLiHsneJYSOd72fNTdIzIKdXx3Ps3vQ8QEIMYcW/eFZBwtNv74+n8lxDb015SVtzKP5tNPBB2depKv+zvq//Ed4TnSLsNcOPCVrajlzYG5A/P+R4NBivVW/FVfO01y+ndBqLECqqhNP6bXFg9BT2cfNitMZ0G/iWECqGNcvCviL4LxCX0oFuaCHf3O8M+uWyTD51evCQfNmwXGbP69gdoiMalh0bRmIMC17VD+BUg/UgHoS/ACcF+yDzaEcSEjtlqHR395X9yGwzjF8nHqYqh/otqKOh9/ApkI7mI4zJyJ/XGG2bOoCr/zKrrU+QNKlS3LAoqqXtC4i/l7Dn7qM/V/Pnq0dLUhMiYWitAa4SgNuzxGW2nPvqlZevIP18Rc9D1y8w7eJgNbMF4PT4iDDXqn4tJ1+IkWKYZzBJbDs4nIYyEEZwUTt/sGMBfvENQJ7lvKL4TdqYe67Tau4wkYPsuNq2AWqLNY3IXtW7iXdwqKtuDeVWS/PIEikb46MVyWloH3stSjnRQflhPBf+3jvomezQA6Sv/1CEkEeDiOpWU99CiaNCS2TYfH4mdavY9vrnYTJtCxfGKcCjN/YFIiz8+/fCD+mxFvEB3p04zxyLgfsoBj4mvd/qu73y01UyN/RusMXbjMHn+Ptv5G18o+kteZi6g4BRY9Ll6hzY7RARx4BNg+yU5MXWdZuwRUmubujk+/ZfV5QyhvUj7945+36UuR/vSicj6aA7ElDwZqCBQ6bGD7uWeWon0a8giFx46hEu1jice3aIhPxqF1ka7kxDkaPf5/dFUafug4srj7SHP6ai4OOoKLQNKaJ57ZvvyurdVMS7PK1uj7eyuAjto5jvWAihmxqDw=
  template:
    metadata:
      creationTimestamp: null
      name: onepassword-token
      namespace: 1password
