{
 "title": "1Password Operator",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "1password" },
   { "name": "pod_query_string", "label": "Pod Query String", "query": "onepassword-connect" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Connect API Request Rate [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(secret_service_api_http_method_counts[5m])",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": "Connect API Average Request Duration [5m]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(secret_service_api_http_duration_seconds_sum{endpoint=\"connect-api\"}[5m])) by (method,path)\n  /\nsum(increase(secret_service_api_http_duration_seconds_count{endpoint=\"connect-api\"}[5m])) by (method,path)",
     "legendFormat": "{{method}}: {{path}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\", type=\"hard\",resource=\"requests.cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\", type=\"hard\",resource=\"limits.cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\", type=\"hard\",resource=\"requests.memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_resourcequota{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\", type=\"hard\",resource=\"limits.memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",resource=\"cpu\"}) by (pod)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",resource=\"cpu\"}) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "pod"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\", resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",container!=\"\", image!=\"\"}) by (pod) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",resource=\"memory\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",container!=\"\"}) by (pod)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\",pod=~\".*$pod_query_string.*\",container!=\"\"}) by (pod)"
    }
   ]
  }
 ]
}