{
 "title": "Cert-Manager (new)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(exported_namespace)\n"
    }
   },
   { "name": "cm_namespace", "label": "Cert-Manager Namespace", "query": "cert-manager" }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Valid Certificates by Issuer",
   "type": "stat",
   "description": "The number of available certificates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"True\", exported_namespace=~\"$namespace\"}) by (issuer_name)",
     "legendFormat": "{{issuer_name}}"
    }
   ]
  },
  {
   "title": "Expiring Certificates by Issuer",
   "type": "stat",
   "description": "The number of certificates that will expire within the next 14 days",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} < (time()+(14*24*3600))) by (issuer_name)",
     "legendFormat": "{{issuer_name}}"
    }
   ]
  },
  {
   "title": "Total ACME Requests by Issuer",
   "type": "stat",
   "description": "Total number of HTTP requests",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count) by (issuer_name)",
     "legendFormat": "{{issuer_name}}"
    }
   ]
  },
  {
   "title": "Time to Expiration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$namespace\"} - time())/(24*3600)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time to Automatic Renewal",
   "type": "bargauge",
   "description": "Time before the certificates are automatically renewed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(certmanager_certificate_renewal_timestamp_seconds{exported_namespace=~\"$namespace\"} - time())/(24*3600)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "cert-manager-cainjector CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$cm_namespace\",container=\"cert-manager-cainjector\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container=\"cert-manager-cainjector\",resource=\"cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container=\"cert-manager-cainjector\",resource=\"cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "cert-manager-webhook CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$cm_namespace\",container=\"cert-manager-webhook\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container=\"cert-manager-webhook\",resource=\"cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container=\"cert-manager-webhook\",resource=\"cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "cert-manager-controller CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$cm_namespace\",container=\"cert-manager-controller\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container=\"cert-manager-controller\",resource=\"cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container=\"cert-manager-controller\",resource=\"cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "cert-manager-cainjector Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$cm_namespace\",container=\"cert-manager-cainjector\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container=\"cert-manager-cainjector\",resource=\"memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container=\"cert-manager-cainjector\",resource=\"memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "cert-manager-cainjector Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$cm_namespace\",container=\"cert-manager-webhook\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container=\"cert-manager-webhook\",resource=\"memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container=\"cert-manager-webhook\",resource=\"memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "cert-manager-controller Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$cm_namespace\",container=\"cert-manager-controller\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container=\"cert-manager-controller\",resource=\"memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container=\"cert-manager-controller\",resource=\"memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$cm_namespace\",container!=\"\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container!=\"\",resource=\"cpu\"}) by (pod,container)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$cm_namespace\",container!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container!=\"\",resource=\"cpu\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container!=\"\",resource=\"cpu\"}) by (pod,container)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$cm_namespace\",container!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container!=\"\",resource=\"cpu\"}) by (pod,container)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$cm_namespace\",container!=\"\", image!=\"\"}) by (pod,container)",
     "legendFormat": "pod"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container!=\"\",resource=\"memory\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$cm_namespace\",container!=\"\", image!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_requests{namespace=\"$cm_namespace\",container!=\"\",resource=\"memory\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container!=\"\", resource=\"memory\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$cm_namespace\",container!=\"\", image!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_limits{namespace=\"$cm_namespace\",container!=\"\",resource=\"memory\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$cm_namespace\",container!=\"\",container!=\"\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$cm_namespace\",container!=\"\",container!=\"\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$cm_namespace\",container!=\"\"}) by (pod,container)"
    }
   ]
  }
 ]
}