{
 "title": "External DNS",
 "tags": [
  "external-dns",
  "dns"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "namespace", "label": "Namespace", "query": "external-dns" }
  ]
 },
 "panels": [
  { "title": "External-DNS Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Endpoints in the Registry",
   "type": "timeseries",
   "description": "This is the total number of records under management in the Zone by External DNS.",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_registry_endpoints_total{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of Endpoints in all Sources",
   "type": "timeseries",
   "description": "Number of Endpoints Provisioned from Sources in the Cluster",
   "gridPos": { "h": 9, "w": 10, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "external_dns_source_endpoints_total{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "External-DNS Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Timestamp of last attempted sync with the DNS provider",
   "type": "bargauge",
   "description": "Timestamp of last attempted sync with the DNS provider",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_last_reconcile_timestamp_seconds{namespace=\"$namespace\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Timestamp of last successful sync with the DNS provider",
   "type": "bargauge",
   "description": "Timestamp of last successful sync with the DNS provider",
   "gridPos": { "h": 3, "w": 8, "x": 7, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_last_sync_timestamp_seconds{namespace=\"$namespace\"}*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "External-dns controller no_op runs total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_no_op_runs_total{namespace=\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "External-DNS Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Number of A records in registry",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_registry_a_records{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of A records in source",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_source_a_records{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Controller Verified A Records",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_verified_a_records{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "External DNS Registry Error Rate [5m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(external_dns_registry_errors_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Number of AAAA records in registry",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_registry_aaaa_records{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Number of AAAA records in source",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_source_aaaa_records{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Controller Verified AAAA Records",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "external_dns_controller_verified_aaaa_records{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "External DNS Source Error Rate [5m]",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(external_dns_source_errors_total{namespace=\"$namespace\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "External-DNS Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container=\"external-dns\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"external-dns\",resource=\"cpu\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"external-dns\",resource=\"cpu\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 11, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container=\"external-dns\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "scalar(kube_pod_container_resource_requests{namespace=\"$namespace\",container=\"external-dns\",resource=\"memory\"})",
     "legendFormat": "quota - requests"
    },
    {
     "expr": "scalar(kube_pod_container_resource_limits{namespace=\"$namespace\",container=\"external-dns\",resource=\"memory\"})",
     "legendFormat": "quota - limits"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 4, "w": 21, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container!=\"\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",container!=\"\",resource=\"cpu\"}) by (pod,container)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",container!=\"\",resource=\"cpu\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container!=\"\",resource=\"cpu\"}) by (pod,container)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\",container!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container!=\"\",resource=\"cpu\"}) by (pod,container)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod,container)",
     "legendFormat": "pod"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",container!=\"\",resource=\"memory\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",container!=\"\",resource=\"memory\"}) by (pod,container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container!=\"\", resource=\"memory\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\",container!=\"\", image!=\"\"}) by (pod,container) / sum(kube_pod_container_resource_limits{namespace=\"$namespace\",container!=\"\",resource=\"memory\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_rss{namespace=\"$namespace\",container!=\"\",container!=\"\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_cache{namespace=\"$namespace\",container!=\"\",container!=\"\"}) by (pod,container)"
    },
    {
     "expr": "sum(container_memory_swap{namespace=\"$namespace\",container!=\"\"}) by (pod,container)"
    }
   ]
  }
 ]
}