apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/projects/argocd.yaml
  - resources/projects/databases.yaml
  - resources/projects/identity.yaml
  - resources/projects/networking.yaml
  - resources/projects/observability.yaml
  - resources/projects/secrets.yaml
  - resources/applications/1password.yaml
  - resources/applications/argocd-appstate.yaml
  - resources/applications/argocd.yaml
  - resources/applications/argo-events.yaml
  - resources/applications/argo-events-bus.yaml
  - resources/applications/argo-workflows.yaml
  - resources/applications/cloud-native-postgres-operator.yaml
  - resources/applications/cmp-example.yaml
  - resources/applicationsets/cert-manager.yaml
  - resources/applicationsets/cert-manager-cluster-issuer.yaml
  - resources/applicationsets/trust-manager.yaml
  - resources/applicationsets/external-dns.yaml
  - resources/applicationsets/gateway-api.yaml
  - resources/applicationsets/haproxy-ingress.yaml
  - resources/applicationsets/haproxy-kubernetes-ingress.yaml
  - resources/applicationsets/keycloak-operator.yaml
  - resources/applicationsets/keycloak.yaml
  - resources/applicationsets/openldap.yaml
  - resources/applicationsets/sealed-secrets.yaml
  - resources/applicationsets/external-secrets-operator.yaml
  - resources/applicationsets/consul.yaml
  - resources/applicationsets/kubernetes-replicator.yaml
  - resources/applicationsets/prometheus-adapter.yaml
  - resources/applicationsets/envoy-gateway.yaml
  - resources/applicationsets/opentelemetry-operator.yaml